# Generated by Django 5.1.2 on 2024-10-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading_network", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=70, verbose_name="Email")),
                ("country", models.CharField(max_length=200, verbose_name="Страна")),
                ("city", models.CharField(max_length=100, verbose_name="Город")),
                (
                    "street",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Улица"
                    ),
                ),
                (
                    "house_number",
                    models.PositiveIntegerField(
                        blank=True, max_length=10, null=True, verbose_name="Номер дома"
                    ),
                ),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
                "ordering": ("city", "country"),
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("title",),
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
