# Generated by Django 5.1.2 on 2024-10-28 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading_network", "0002_contact_alter_product_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="Название")),
                (
                    "supplier_type",
                    models.CharField(
                        choices=[
                            ("factory", "Завод"),
                            ("retail_network", "Розничная сеть"),
                            (
                                "individual_entrepreneur",
                                "Индивидуальный предприниматель",
                            ),
                        ],
                        max_length=40,
                        verbose_name="Тип поставщика",
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        max_length=10, verbose_name="Уровень в иерархии"
                    ),
                ),
                (
                    "debt",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                        verbose_name="Задолженность перед поставщиком",
                    ),
                ),
                (
                    "creation_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="trading_network.provider",
                        verbose_name="Поставщик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Поставщик",
                "verbose_name_plural": "Поставщики",
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="contact",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="trading_network.provider",
                verbose_name="Поставщик",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="trading_network.provider",
                verbose_name="Поставщик",
            ),
        ),
    ]
