# Generated by Django 5.1.2 on 2024-10-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading_network", "0003_provider_contact_supplier_product_supplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="house_number",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Номер дома"
            ),
        ),
        migrations.AlterField(
            model_name="provider",
            name="level",
            field=models.IntegerField(verbose_name="Уровень в иерархии"),
        ),
    ]
